return {

  -- {
  --   'zbirenbaum/copilot.lua',
  --   event = 'InsertEnter',
  --   cmd = 'Copilot',
  --   build = ':Copilot auth',
  --   opts = {
  --     panel = { enabled = false },
  --     suggestion = { enabled = false },
  --     filetypes = {
  --       markdown = true,
  --       help = true,
  --     },
  --   },
  -- },
  -- {
  --   'zbirenbaum/copilot-cmp',
  --   opts = {},
  --   config = function(_, opts)
  --     local copilot_cmp = require 'copilot_cmp'
  --     copilot_cmp.setup(opts)
  --   end,
  -- },
  -- {
  --   'CopilotC-Nvim/CopilotChat.nvim',
  --   branch = 'canary',
  --   dependencies = {
  --     { 'zbirenbaum/copilot.lua' },
  --     { 'nvim-lua/plenary.nvim' },
  --   },
  --   config = function()
  --     require('CopilotChat').setup()
  --   end,
  -- },
}
